### ISSUE TITLE
Exception thrown when trying to run docker-compose up --build

### ISSUE THREAD

**Issue by tommyready** [supermavster/docker-laravel-8#13]
When trying to run docker up I get the following exception:

```
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 81, in main
  File "compose\cli\main.py", line 200, in perform_command
  File "compose\cli\command.py", line 60, in project_from_options
  File "compose\cli\command.py", line 152, in get_project
  File "compose\cli\docker_client.py", line 41, in get_client
  File "compose\cli\docker_client.py", line 170, in docker_client
  File "docker\api\client.py", line 197, in __init__
  File "docker\api\client.py", line 221, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')
[1380] Failed to execute script docker-compose
```

Anyone else getting this message? Any help would be great!

**Comment by tommyready** [comment]
Issue was with my docker install, not this project.
